---
- name: Install Nginx, MySQL, and PHP
  hosts: web_servers
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mysql-server
        - php-fpm
        - php-mysql
        - python3-pip

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Configure PHP
      lineinfile:
        path: /etc/php/8.1/fpm/php.ini
        line: "{{ item }}"
      with_items:
        - 'cgi.fix_pathinfo=0'
      notify: Restart PHP

    - name: Start MySQL service
      service:
        name: mysql
        state: started
      notify: Enable MySQL on boot

    - name: Save root password in .my.cnf
      template:
        src: root_cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: '0600'

    - name: Create MySQL database and user
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: mydatabase
        state: present
      notify: Enable MySQL on boot

    - name: Run phpinfo() command
      shell: "echo '<?php phpinfo(); ?>' > /var/www/html/index.php"
      notify: Restart PHP

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart PHP
      service:
        name: php8.1-fpm
        state: restarted

    - name: Enable MySQL on boot
      service:
        name: mysql
        enabled: yes
        state: restarted

